postgres:
  host: 8.148.188.209
  port: 5432
  dbname: quant_lab
  user: postgres
  password: postgres
  sslmode: disable
  search_path: public
  ssh:
    enabled: true
    host: 8.148.188.209
    port: 22
    user: Administrator
    password: Lbdc191500
    password_env: SSH_PASSWORD
    remote_bind_host: 127.0.0.1
    remote_bind_port: 5432

data:
  - name: BTCUSDT_tick
    source: postgres
    code: BTCUSDT
    code_col: instrument_id
    data_type: tick
    timeframe: minutes
    compression: 1
    start: "2026-04-10"
    end: "2026-04-10"

strategy:
  name: cta_trend
  params:
    fast: 10
    slow: 30
    risk_per_trade: 0.0001

broker:
  starting_cash: 100000000.0
  account_mode: cash

commission_default:
  commission: 0.0003
  mult: 1
  margin: 0
  commtype: perc

symbols:
  BTCUSDT_tick:
    mult: 1
    commission: 0.0003
    margin: 0
    commtype: perc

engine:
  name: backtrader
  cash: 100000000
  commission: 0.0003
